/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react';
import { useGLTF, useAnimations } from '@react-three/drei';

// GLTF Loader for Three models
// Not used
export default function Warrior(props) {
	const group = useRef();
	const { nodes, materials, animations } = useGLTF('/Warrior.gltf');
	const { actions } = useAnimations(animations, group);

	return (
		<group ref={group} {...props} dispose={null}>
			<group name="Armature" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
				<primitive object={nodes.Hips} />
				<skinnedMesh
					geometry={nodes.Maria_J_J_Ong.geometry}
					material={nodes.Maria_J_J_Ong.material}
					skeleton={nodes.Maria_J_J_Ong.skeleton}
				/>
				<skinnedMesh
					geometry={nodes.Maria_sword.geometry}
					material={nodes.Maria_sword.material}
					skeleton={nodes.Maria_sword.skeleton}
				/>
			</group>
		</group>
	);
}

useGLTF.preload('/Warrior.glb');
