/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react';
import { useGLTF, useAnimations } from '@react-three/drei';

export default function r(props) {
	const group = useRef();
	const { nodes, materials, animations } = useGLTF('/Animation2.glb.gltf');
	const { actions } = useAnimations(animations, group);
	return (
		<group ref={group} {...props} dispose={null}>
			<group name="RL_ExtendedRoot" scale={0.01}>
				<group
					name="CC_Base_Tongue01"
					position={[3.33, 0, -1.03]}
					rotation={[0, 0.11, 0]}>
					<group
						name="CC_Base_Tongue02"
						position={[1.17, 0, 0]}
						rotation={[0, 0.17, 0]}
					/>
				</group>
			</group>
			<group name="Armature" scale={0.01}>
				<primitive object={nodes.RL_BoneRoot} />
				<skinnedMesh
					name="Cesar_D_LaTorre_Jacket"
					geometry={nodes.Cesar_D_LaTorre_Jacket.geometry}
					material={materials.Character}
					skeleton={nodes.Cesar_D_LaTorre_Jacket.skeleton}
					morphTargetDictionary={
						nodes.Cesar_D_LaTorre_Jacket.morphTargetDictionary
					}
					morphTargetInfluences={
						nodes.Cesar_D_LaTorre_Jacket.morphTargetInfluences
					}
				/>
			</group>
			<group name="RL_ExtendedRoot001" scale={0.01}>
				<group
					name="CC_Base_Tongue01001"
					position={[3.33, 0, -1.03]}
					rotation={[0, 0.11, 0]}>
					<group
						name="CC_Base_Tongue02001"
						position={[1.17, 0, 0]}
						rotation={[0, 0.17, 0]}
					/>
				</group>
			</group>
		</group>
	);
}

useGLTF.preload('/Animation2.glb.gltf');
